"""Nearmap Coverage Fetcher (GDAL-free port) and Data Fetcher.

This is a faithful port of ``../nearmap/utils/aipack_transaction.py`` adapted for
this repository. The tiling algorithm, UTM area calculation, ``simplify(0.0001)``
vertex reduction, and the ``GET /coverage/v2/tx/poly/{coords}`` endpoint are
reproduced exactly as validated in the ``nearmap`` repo
(``tests/credit_validation_findings.md``).

The only intentional differences from the original:

1. **No GDAL stack.** The original used ``geopandas`` + ``fiona`` for file IO and
   UTM reprojection. This port uses ``shapely`` + ``pyproj`` (already installed in
   this repo) so no new dependencies are required. The tiling *math* is identical;
   the offline validation in ``validation/test_offline.py`` proves the tiler
   reproduces the cached coverage plans generated by the original code.
2. **In-memory geometry input.** The UI feeds a drawn/uploaded GeoJSON geometry
   rather than a file path, so ``polygons_from_geometry()`` is added alongside the
   file-based ``read_polygons_from_file()``.
3. **Arbitrary resource string.** ``get_coverage_for_tile()`` accepts the UI's full
   comma-joined ``resources`` string (e.g. ``"raster:Vert,aiPacks:building"``) in a
   single call per tile, instead of one hardcoded AI pack. Per validation finding
   T4, the API bills the comma-separated request as the sum of the per-resource
   costs (no bundle discount), so one combined call equals N single-resource calls.

``DataFetcher`` is copied faithfully (it has no GDAL dependencies). The cost
estimator UI never downloads features, so ``DataFetcher`` is unused here but kept
for fidelity / future use.
"""

from __future__ import annotations

import json
import math
import time
from datetime import datetime
from pathlib import Path
from typing import Callable, Dict, List, Optional, Tuple

import requests
import shapely.ops
from pyproj import Transformer
from shapely.geometry import Polygon, box, mapping, shape


class CoverageFetcher:
    """Plan coverage and (optionally) acquire transaction tokens.

    preview=True: Cost estimation only (no charges)
    preview=False: Charges credits and returns transaction tokens
    """

    # Available AI pack resources (kept for reference / parity with the original).
    AI_PACKS = {
        "building": "aiPacks:building",
        "building_char": "aiPacks:building_char",
        "construction": "aiPacks:construction",
        "debris": "aiPacks:debris",
        "pavement_marking": "aiPacks:pavement_marking",
        "poles": "aiPacks:poles",
        "pool": "aiPacks:pool",
        "postcat": "aiPacks:postcat",
        "roof_char": "aiPacks:roof_char",
        "roof_cond": "aiPacks:roof_cond",
        "roof_objects": "aiPacks:roof_objects",
        "solar": "aiPacks:solar",
        "surface_permeability": "aiPacks:surface_permeability",
        "surfaces": "aiPacks:surfaces",
        "trampoline": "aiPacks:trampoline",
        "vegetation": "aiPacks:vegetation",
    }

    def __init__(self, api_key: str = "", max_area_sqm: float = 300000):
        """Initialize Coverage Fetcher.

        Args:
            api_key: Nearmap API key (may be empty for tiling-only use).
            max_area_sqm: Maximum area per tile in square meters (default 300k).
                NOTE: validated to be a SOFT target — tiles can exceed it (the tiler
                computes a uniform grid once and clips, without recursive splitting).
        """
        self.api_key = api_key
        self.max_area_sqm = max_area_sqm
        self.base_url = "https://api.nearmap.com"
        self.session = requests.Session()
        if api_key:
            self.session.headers.update({"Authorization": f"Bearer {api_key}"})

    def set_api_key(self, api_key: str) -> None:
        """Set/replace the API key (and the Authorization header)."""
        self.api_key = api_key
        if api_key:
            self.session.headers.update({"Authorization": f"Bearer {api_key}"})

    # --- geometry input ------------------------------------------------------

    def read_polygons_from_file(self, file_path: str) -> List[Polygon]:
        """Read polygons from a GeoJSON file (assumed EPSG:4326 / CRS84 lon,lat).

        Replaces the original geopandas-based ``read_geometries`` for the formats
        this repo actually uses (GeoJSON). KML is not supported here (the UI only
        accepts ``.geojson``/``.json``).
        """
        path = Path(file_path)
        if not path.exists():
            raise FileNotFoundError(f"File not found: {file_path}")

        data = json.loads(path.read_text())
        geoms = self._geojson_to_geometries(data)
        if not geoms:
            raise ValueError("No polygon geometries found in file")
        return self._normalize_polygons(geoms)

    def polygons_from_geometry(self, geometry: Dict) -> List[Polygon]:
        """Extract polygons from an in-memory GeoJSON object.

        Accepts a FeatureCollection, a Feature, or a bare geometry dict.
        """
        geoms = self._geojson_to_geometries(geometry)
        if not geoms:
            raise ValueError("No polygon geometries found in geometry input")
        return self._normalize_polygons(geoms)

    @staticmethod
    def _geojson_to_geometries(obj: Dict) -> List:
        """Turn a GeoJSON FeatureCollection/Feature/geometry into shapely geoms."""
        if not isinstance(obj, dict):
            raise ValueError("Geometry input must be a GeoJSON dict")
        gtype = obj.get("type")
        if gtype == "FeatureCollection":
            return [shape(f["geometry"]) for f in obj.get("features", []) if f.get("geometry")]
        if gtype == "Feature":
            return [shape(obj["geometry"])] if obj.get("geometry") else []
        # bare geometry
        return [shape(obj)]

    @staticmethod
    def _normalize_polygons(geoms: List) -> List[Polygon]:
        """Fix invalid geometries (buffer(0)) and explode to a flat polygon list."""
        polygons: List[Polygon] = []
        for geom in geoms:
            if not geom.is_valid:
                geom = geom.buffer(0)
            if geom.geom_type == "Polygon":
                polygons.append(geom)
            elif geom.geom_type == "MultiPolygon":
                polygons.extend(list(geom.geoms))
            else:
                raise ValueError(f"Unsupported geometry type: {geom.geom_type}")
        return polygons

    # Kept for naming parity with the original API.
    def extract_all_polygons(self, geoms: List) -> List[Polygon]:
        return self._normalize_polygons(geoms)

    # --- area + tiling (faithful to the original algorithm) ------------------

    def calculate_polygon_area_sqm(self, polygon: Polygon) -> float:
        """Calculate polygon area in square meters using a UTM projection.

        Identical projection choice to the original geopandas code; using pyproj
        directly yields the same area (geopandas delegates to pyproj).
        """
        centroid = polygon.centroid
        lon, lat = centroid.x, centroid.y
        utm_zone = int((lon + 180) / 6) + 1
        hemisphere = "north" if lat >= 0 else "south"
        utm_crs = f"+proj=utm +zone={utm_zone} +{hemisphere} +ellps=WGS84"
        transformer = Transformer.from_crs("EPSG:4326", utm_crs, always_xy=True)
        projected = shapely.ops.transform(transformer.transform, polygon)
        return projected.area

    def tile_polygon(
        self, polygon: Polygon, polygon_id: int = 0, verbose: bool = False
    ) -> List[Tuple[Polygon, int]]:
        """Tile polygon into smaller tiles based on max_area_sqm."""
        area_sqm = self.calculate_polygon_area_sqm(polygon)
        if area_sqm <= self.max_area_sqm:
            return [(polygon, polygon_id)]

        n_tiles = int(math.ceil(area_sqm / self.max_area_sqm))
        n_cols = int(math.ceil(math.sqrt(n_tiles)))
        n_rows = int(math.ceil(n_tiles / n_cols))

        minx, miny, maxx, maxy = polygon.bounds
        tile_width = (maxx - minx) / n_cols
        tile_height = (maxy - miny) / n_rows
        tiles: List[Tuple[Polygon, int]] = []
        for i in range(n_rows):
            for j in range(n_cols):
                tile_box = box(
                    minx + j * tile_width,
                    miny + i * tile_height,
                    minx + (j + 1) * tile_width,
                    miny + (i + 1) * tile_height,
                )

                if tile_box.intersects(polygon):
                    clipped = tile_box.intersection(polygon)
                    if clipped.is_empty:
                        continue

                    if clipped.geom_type == "MultiPolygon":
                        for component in clipped.geoms:
                            if component.geom_type == "Polygon":
                                # simplify to reduce vertex count (long-URL guard)
                                component = component.simplify(0.0001, preserve_topology=True)
                                coords = list(component.exterior.coords)
                                if len(coords) >= 4:
                                    tiles.append((component, polygon_id))
                    elif clipped.geom_type == "Polygon":
                        clipped = clipped.simplify(0.0001, preserve_topology=True)
                        coords = list(clipped.exterior.coords)
                        if len(coords) >= 4:
                            tiles.append((clipped, polygon_id))

        if verbose:
            print(f"  Polygon {polygon_id}: {area_sqm:.0f} sqm -> {len(tiles)} tiles")
        return tiles

    def deduplicate_tiles(
        self, tiles_with_ids: List[Tuple[Polygon, int]]
    ) -> Tuple[List[Polygon], Dict[int, List[int]]]:
        """Deduplicate tiles based on geometry (WKT)."""
        unique_tiles: List[Polygon] = []
        tile_to_sources: Dict[int, List[int]] = {}
        seen_wkts: Dict[str, int] = {}

        for tile, source_id in tiles_with_ids:
            wkt = tile.wkt
            if wkt not in seen_wkts:
                tile_idx = len(unique_tiles)
                seen_wkts[wkt] = tile_idx
                unique_tiles.append(tile)
                tile_to_sources[tile_idx] = [source_id]
            else:
                tile_idx = seen_wkts[wkt]
                if source_id not in tile_to_sources[tile_idx]:
                    tile_to_sources[tile_idx].append(source_id)

        return unique_tiles, tile_to_sources

    def generate_tiles(
        self, geometry: Dict
    ) -> Tuple[List[Polygon], Dict[int, List[int]], List[Polygon]]:
        """Read + tile + deduplicate an in-memory geometry.

        Returns (unique_tiles, tile_to_sources, source_polygons). Pure-local — makes
        no API calls — so the UI can show the tile/call count before charging time.
        """
        polygons = self.polygons_from_geometry(geometry)
        tiles_with_ids: List[Tuple[Polygon, int]] = []
        for idx, polygon in enumerate(polygons):
            tiles_with_ids.extend(self.tile_polygon(polygon, polygon_id=idx))
        unique_tiles, tile_to_sources = self.deduplicate_tiles(tiles_with_ids)
        return unique_tiles, tile_to_sources, polygons

    # --- API ----------------------------------------------------------------

    def polygon_to_api_string(self, polygon: Polygon) -> str:
        """Convert polygon to the Nearmap tx/poly coordinate string (lon,lat,...)."""
        if not polygon.is_valid:
            polygon = polygon.buffer(0)
        coords = list(polygon.exterior.coords)
        coord_pairs = [f"{coord[0]},{coord[1]}" for coord in coords]
        if len(coord_pairs) < 4:
            raise ValueError("Polygon must have at least 3 points plus closing point")
        return ",".join(coord_pairs)

    def get_coverage_for_tile(
        self,
        tile: Polygon,
        resources: str,
        tile_idx: int,
        preview: bool = True,
        since: Optional[str] = None,
        until: Optional[str] = None,
        dates: str = "single",
    ) -> Dict:
        """Get coverage information for a single tile via GET /coverage/v2/tx/poly."""
        poly_string = self.polygon_to_api_string(tile)
        url = f"{self.base_url}/coverage/v2/tx/poly/{poly_string}"
        params = {
            # The API rejects spaces in the resources param; the UI joins with ", ".
            "resources": resources.replace(" ", ""),
            "dates": dates,
            "preview": "true" if preview else "false",
            "apikey": self.api_key,
        }
        if since:
            params["since"] = since
        if until:
            params["until"] = until

        response = self.session.get(url, params=params)
        response.raise_for_status()
        return response.json()

    def plan_coverage_for_tiles(
        self,
        unique_tiles: List[Polygon],
        tile_to_sources: Dict[int, List[int]],
        resources: str,
        preview: bool = True,
        since: Optional[str] = None,
        until: Optional[str] = None,
        dates: str = "single",
        sleep: float = 0.5,
        progress_cb: Optional[Callable[[int, int, int, int], None]] = None,
    ) -> Dict:
        """Query coverage for pre-tiled polygons and build a coverage plan.

        On a per-tile error (e.g. 404 SURVEYS_NOT_FOUND for ocean/uncovered tiles),
        the tile is skipped and counted as failed — it contributes 0 to the total.
        ``progress_cb(done, total, total_cost, failed)`` is called after each tile so
        the UI can render a progress bar.
        """
        tile_coverage_data: List[Dict] = []
        total_cost = 0
        failed = 0
        total = len(unique_tiles)

        for idx, tile in enumerate(unique_tiles):
            try:
                coverage = self.get_coverage_for_tile(
                    tile, resources, idx, preview=preview, since=since, until=until, dates=dates
                )
                tile_data = {
                    "tile_id": idx,
                    "source_polygons": tile_to_sources.get(idx, []),
                    "coverage": coverage,
                    "geometry": mapping(tile),
                    "area_sqm": self.calculate_polygon_area_sqm(tile),
                }
                tile_coverage_data.append(tile_data)
                total_cost += coverage.get("costOfTransaction", 0)
            except Exception:
                failed += 1
            finally:
                if progress_cb:
                    progress_cb(idx + 1, total, total_cost, failed)
                if sleep:
                    time.sleep(sleep)

        coverage_plan = {
            "metadata": {
                "preview_mode": preview,
                "resources": resources,
                "max_area_sqm": self.max_area_sqm,
                "date_filter_since": since,
                "date_filter_until": until,
                "date_filter_mode": dates,
            },
            "summary": {
                "unique_tiles": total,
                "tiles_with_coverage": len(tile_coverage_data),
                "tiles_failed": failed,
                "total_estimated_cost_credits": total_cost,
            },
            "tiles": tile_coverage_data,
        }
        return coverage_plan

    def plan_coverage(
        self,
        geometry_file: str,
        resources: str,
        preview: bool = True,
        since: Optional[str] = None,
        until: Optional[str] = None,
        dates: str = "single",
        sleep: float = 0.5,
        progress_cb: Optional[Callable[[int, int, int, int], None]] = None,
    ) -> Dict:
        """Plan coverage for a GeoJSON file (used by the live validation script)."""
        polygons = self.read_polygons_from_file(geometry_file)
        tiles_with_ids: List[Tuple[Polygon, int]] = []
        for idx, polygon in enumerate(polygons):
            tiles_with_ids.extend(self.tile_polygon(polygon, polygon_id=idx))
        unique_tiles, tile_to_sources = self.deduplicate_tiles(tiles_with_ids)
        plan = self.plan_coverage_for_tiles(
            unique_tiles, tile_to_sources, resources,
            preview=preview, since=since, until=until, dates=dates,
            sleep=sleep, progress_cb=progress_cb,
        )
        plan["metadata"]["geometry_file"] = str(geometry_file)
        plan["metadata"]["input_features"] = len(polygons)
        return plan


def sum_plan_cost(plan: Dict) -> int:
    """Sum costOfTransaction across a coverage plan's tiles.

    Shared by the live estimator and the offline validation so the aggregation
    logic is tested against the cached plans without any API calls.
    """
    return sum(t.get("coverage", {}).get("costOfTransaction", 0) for t in plan.get("tiles", []))


class DataFetcher:
    """Download AI features using transaction tokens from a coverage plan.

    Faithful copy from ``../nearmap/utils/aipack_transaction.py`` (no GDAL deps).
    Unused by the cost estimator UI (which only previews cost), kept for fidelity.
    Requires a coverage plan created with preview=False.
    """

    def __init__(self, api_key: str):
        self.api_key = api_key
        self.base_url = "https://api.nearmap.com"
        self.session = requests.Session()
        self.session.headers.update({"Authorization": f"Bearer {api_key}"})

    def download_tile_features(
        self,
        ai_resource_id: str,
        transaction_token: str,
        output_file: str,
        tile_idx: int,
    ) -> Dict:
        """Download AI features for a single tile."""
        url = f"{self.base_url}/ai/features/v4/tx/surveyresources/{ai_resource_id}/features.json"
        params = {"transactionToken": transaction_token}
        response = self.session.get(url, params=params)
        response.raise_for_status()
        data = response.json()
        with open(output_file, "w") as f:
            json.dump(data, f, indent=2)
        feature_count = len(data.get("features", []))
        return {"feature_count": feature_count, "output_file": str(output_file)}

    def execute_coverage_plan(
        self, coverage_plan: Dict, output_dir: str, output_file: Optional[str] = None
    ) -> Dict:
        """Execute coverage plan and download all data using transaction tokens."""
        metadata = coverage_plan.get("metadata", {})
        if metadata.get("preview_mode", True):
            raise ValueError("Plan created in preview mode. Re-run with preview=False.")

        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

        tile_files: List[str] = []
        download_results: List[Dict] = []

        for tile_data in coverage_plan["tiles"]:
            tile_idx = tile_data["tile_id"]
            coverage = tile_data["coverage"]
            if not coverage.get("surveys"):
                continue
            transaction_token = coverage.get("transactionToken")
            survey = coverage["surveys"][0]
            ai_resource_id = survey.get("aiResourceId")
            if not ai_resource_id or not transaction_token:
                continue
            try:
                tile_output = output_path / f"tile_{tile_idx}_{timestamp}.json"
                result = self.download_tile_features(
                    ai_resource_id, transaction_token, str(tile_output), tile_idx
                )
                tile_files.append(str(tile_output))
                download_results.append(result)
                time.sleep(1)
            except Exception as e:
                print(f"  Tile {tile_idx + 1}: Failed - {e}")
                continue

        merged_file = None
        if output_file and tile_files:
            merged_file = self.merge_tile_features(tile_files, output_file)

        return {
            "plan_metadata": coverage_plan["metadata"],
            "execution": {
                "timestamp": datetime.now().isoformat(),
                "tiles_attempted": len(coverage_plan["tiles"]),
                "tiles_downloaded": len(tile_files),
            },
            "files": {"tile_files": tile_files, "merged_file": merged_file},
        }

    def merge_tile_features(self, tile_files: List[str], output_file: str) -> str:
        """Merge multiple tile feature files into a single GeoJSON."""
        all_features: List[Dict] = []
        for file_path in tile_files:
            try:
                with open(file_path, "r") as f:
                    data = json.load(f)
                for feature in data.get("features", []):
                    geojson_feature = {
                        "type": "Feature",
                        "geometry": feature.get("geometry"),
                        "properties": {
                            "id": feature.get("id"),
                            "classId": feature.get("classId"),
                            "description": feature.get("description", "Unknown"),
                            "confidence": feature.get("confidence"),
                            "fidelity": feature.get("fidelity"),
                            "areaSqm": feature.get("areaSqm"),
                            "areaSqft": feature.get("areaSqft"),
                            "surveyDate": feature.get("surveyDate"),
                            "meshDate": feature.get("meshDate"),
                        },
                    }
                    if feature.get("attributes"):
                        for attr in feature["attributes"]:
                            geojson_feature["properties"].update(attr)
                    all_features.append(geojson_feature)
            except Exception as e:
                print(f"  Error reading {file_path}: {e}")

        combined_geojson = {
            "type": "FeatureCollection",
            "metadata": {
                "source": "Nearmap AI Features",
                "tile_count": len(tile_files),
                "feature_count": len(all_features),
            },
            "features": all_features,
        }
        output_path = Path(output_file)
        with open(output_path, "w") as f:
            json.dump(combined_geojson, f, indent=2)
        return str(output_path)
