"""Generate REPORT.md: an offline comparison of by_area vs by_api_return.

Runs entirely against the cached coverage plans (no API key, no network). Produces:
  1. A per-plan table: reproduced tiling, API total (= by_api_return), by_area, ratio.
  2. A failed-tile / undercount note (caveat A) using the all-failed plan.
  3. A SYNTHETIC multi-pack section (caveat C) showing how by_area's 7-pack cap
     diverges from per-pack billing as the number of AI packs grows.

Run: ``python -m cost_estimation.validation.generate_report``
"""

from __future__ import annotations

from pathlib import Path

from cost_estimation.by_area import estimate_by_area

from . import cases

OUT = Path(__file__).resolve().parent / "REPORT.md"


def _fmt(n) -> str:
    return f"{n:,}" if isinstance(n, (int, float)) else str(n)


def per_plan_rows():
    rows = []
    for path in cases.plan_paths():
        plan = cases.load_plan(path)
        name = cases.plan_name(path)
        summary = plan["summary"]
        resource = cases.plan_resource(plan)
        api_total = summary["total_estimated_cost_credits"]
        unique = summary["unique_tiles"]
        covered = summary["tiles_with_coverage"]

        aoi = cases.aoi_path_for(name)
        repro = "-"
        repro_ok = "-"
        by_area_val = "-"
        ratio = "-"
        if aoi is not None:
            tiles, _ = cases.tile_aoi(aoi, plan["metadata"].get("max_area_sqm", 300000))
            repro = len(tiles)
            repro_ok = "OK" if repro == unique else "DIFF"
            if cases.resource_in_rate_table(resource) and api_total > 0:
                area = cases.aoi_albers_area(aoi)
                dates = plan["metadata"].get("date_filter_mode", "single")
                ba = estimate_by_area({}, [resource], dates, area_sqm=area)
                by_area_val = ba
                ratio = f"{ba / api_total:.3f}"
        rows.append(
            dict(
                name=name, resource=resource, unique=unique, covered=covered,
                failed=unique - covered, api_total=api_total, repro=repro,
                repro_ok=repro_ok, by_area=by_area_val, ratio=ratio,
            )
        )
    return rows


def synthetic_multipack():
    """Show cap-at-7 divergence on adelaide_sample using building's per-pack cost."""
    aoi = cases.aoi_path_for("adelaide_sample")
    base_plan = cases.PLANS_DIR / "adelaide_sample_building_preview.json"
    if aoi is None or not base_plan.exists():
        return None
    per_pack_api = cases.load_plan(base_plan)["summary"]["total_estimated_cost_credits"]
    area = cases.aoi_albers_area(aoi)
    ai_keys = [k for k in cases.RATE_TABLE if k.startswith("aiPacks:")]

    rows = []
    for n in [1, 5, 7, 8, 10, 16]:
        if n > len(ai_keys):
            break
        selected = ai_keys[:n]
        by_area = estimate_by_area({}, selected, "single", area_sqm=area)
        by_api_proj = per_pack_api * n  # per-pack billing (validated T2/T4)
        ratio = by_area / by_api_proj if by_api_proj else 0
        rows.append((n, by_area, by_api_proj, ratio))
    return per_pack_api, area, rows


def build_report() -> str:
    rows = per_plan_rows()
    lines = []
    lines.append("# Cost Estimation — Offline Validation Report\n")
    lines.append(
        "Generated by `python -m cost_estimation.validation.generate_report`. "
        "All figures are offline, derived from the cached `data/credit_plans/*.json` "
        "(snapshot from the ../nearmap repo, preview=true, May 2026). **No API calls.**\n"
    )
    lines.append("## 1. Per-plan comparison\n")
    lines.append(
        "- **api_total** = `by_api_return` (sum of per-tile `costOfTransaction`).\n"
        "- **repro** = unique tiles produced by this repo's GDAL-free tiler; "
        "**repro_ok** = matches the cached `unique_tiles`.\n"
        "- **by_area** = legacy estimator for the same single resource over the full AOI "
        "(Albers area). **ratio** = by_area / api_total.\n"
        "- **failed** = `unique_tiles - tiles_with_coverage` (tiles that errored, e.g. ocean; "
        "they contribute 0 — caveat A).\n"
    )
    lines.append(
        "| plan | resource | unique | covered | failed | api_total | repro | repro_ok | by_area | ratio |"
    )
    lines.append("|---|---|--:|--:|--:|--:|--:|:--:|--:|--:|")
    for r in rows:
        lines.append(
            f"| {r['name']} | {r['resource']} | {_fmt(r['unique'])} | {_fmt(r['covered'])} | "
            f"{_fmt(r['failed'])} | {_fmt(r['api_total'])} | {_fmt(r['repro'])} | {r['repro_ok']} | "
            f"{_fmt(r['by_area'])} | {r['ratio']} |"
        )
    lines.append("")

    lines.append("## 2. Failed-tile undercount (caveat A)\n")
    pav = next((r for r in rows if "pavement_condition" in r["name"]), None)
    if pav:
        lines.append(
            f"`{pav['name']}` requested an invalid resource (`{pav['resource']}`), so all "
            f"{_fmt(pav['unique'])} tiles errored and were skipped. The plan total reads "
            f"**{_fmt(pav['api_total'])} credits** — a silently-low number. The UI surfaces "
            "`tiles_failed` so this can't be mistaken for an authoritative estimate.\n"
        )

    lines.append("## 3. Synthetic multi-pack divergence (caveat C)\n")
    syn = synthetic_multipack()
    if syn:
        per_pack_api, area, srows = syn
        lines.append(
            f"Offline data is single-pack, so the cap-at-7 bug isn't visible above. "
            f"Using adelaide_sample (~{area/1e6:.2f} km², per-pack API cost "
            f"= {_fmt(per_pack_api)} credits) and projecting per-pack billing "
            "(validated T2/T4: each pack is a separate charge):\n"
        )
        lines.append("| AI packs selected | by_area | by_api_return (projected) | ratio |")
        lines.append("|--:|--:|--:|--:|")
        for n, ba, proj, ratio in srows:
            lines.append(f"| {n} | {_fmt(ba)} | {_fmt(proj)} | {ratio:.3f} |")
        lines.append(
            "\n`by_area` stops growing after 7 packs (the refuted bundle assumption), so it "
            "increasingly **under-estimates** as more packs are selected — the key reason "
            "`by_api_return` is the more correct figure.\n"
        )
    return "\n".join(lines)


def main():
    report = build_report()
    OUT.write_text(report, encoding="utf-8")
    print(f"Wrote {OUT}")


if __name__ == "__main__":
    main()
